= Setting the Account Password

Like with `+useradd+`, you must have root access to use this command.
Set the password for the guest account you created in the previous step
using the following command:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
echo rhel | passwd --stdin guest
----

.Output
[source,bash]
----
Changing password for user guest.
passwd: all authentication tokens updated successfully.
----

This command will set the password in one line by using the `+--stdin+`
option. This is useful when setting passwords inside a script or any
other case when you want to avoid interactively setting the password. If
you instead call `+passwd guest+`, you get a chance to type the password
interactively to set it.

Here you use a four-character password for simplicity, but it is best
practice to select a more secure password. In fact, non-root users would
be unable to use the password *rhel* for their account because it is too
short and does not contain a number or uppercase letter. Root users can
bypass these guidelines if they wish.

Validate the password by using the list (`+-l+`) option for the
`+chage+` command:

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
chage -l guest
----

.Output
[source,bash]
----
Last password change                                    : Mar 07, 2025
Password expires                                        : never
Password inactive                                       : never
Account expires                                         : never
Minimum number of days between password change          : 0
Maximum number of days between password change          : 99999
Number of days of warning before password expires       : 7
----

This outputs useful information about when the password was last
changed, when the password expires, and how long the user will have to
change their password before it becomes inactive.

NOTE: You can view this same information with the `+passwd+` command
using various options, but `+chage -l+` provides it in a much more
human-readable and concise format.

You can use the `+passwd+` command for many more actions, such as
setting an expiration date or locking users from logging in with their
password. Check out the Enable Sysadmin article
https://www.redhat.com/sysadmin/managing-users-passwd[Managing Linux
users with the passwd command^] for more information on these actions.
